// <auto-generated />
namespace MVC_EV_FINAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class script : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(script));
        
        string IMigrationMetadata.Id
        {
            get { return "202303311051415_script"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
